[package]
name = "rbrb"
version = "0.0.1"
edition = "2021"

authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
description = "Write robust rollback networked games"
license = "MIT"
repository = "https://github.com/shelbyd/rbrb"

[dependencies]
